CREATE TABLE "TempTelephone_Interview" (
  "ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
  "Lookup_Fields" VARCHAR2(4000),
  "name_qc_unit" VARCHAR2(4000),
  "address_qc_unit" VARCHAR2(4000),
  "address_city_qc_unit" VARCHAR2(4000),
  "case_name" VARCHAR2(4000),
  "form_date" DATE,
  "mail_address" VARCHAR2(4000),
  "rev_number" Number,
  "apid" NUMBER,
  "TAO" VARCHAR2(4000),
  "Dear" VARCHAR2(4000),
  "v_ForMthOf" VARCHAR2(4000),
  "interview_date" DATE,
  "interview_time" VARCHAR2(4000),
  "mobile_number" VARCHAR2(4000),
  "is_available" NUMBER(1,0),
  "Unearned_Income" NUMBER(1,0),
  "Pay_Stubs" NUMBER(1,0),
  "StubsFrom" DATE,
  "StubsTo" DATE,
  "Rent" NUMBER(1,0),
  "Utility" NUMBER(1,0),
  "landlord" NUMBER(1,0),
  "ForMthOf" VARCHAR2(4000),
  "signed" NUMBER(1,0),
  "other" NUMBER(1,0),
  "memo" VARCHAR2(4000),
  "QCReviewerPhone" VARCHAR2(4000),
  "Unbound" VARCHAR2(4000),
  "reviewer" VARCHAR2(4000),
  PRIMARY KEY ("ID") USING INDEX ENABLE
);