CREATE TABLE "QC24_reclose_FORM" (
  "ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
  "name_qc_unit" VARCHAR2(4000),
  "address_qc_unit" VARCHAR2(4000),
  "address_city_qc_unit" VARCHAR2(4000),
  "look_up_fields" VARCHAR2(4000),
  "tao_address" VARCHAR2(4000),
  "ssn" NUMBER,
  "apid" NUMBER,
  "review" NUMBER,
  "case" VARCHAR2(4000),
  "category" VARCHAR2(4000),
  "dear_text" VARCHAR2(4000),
  "QUALITY_CNTRL_SUPER" VARCHAR2(4000),
  "DECLARE_STATEMENT" VARCHAR2(4000),
  PRIMARY KEY ("ID") USING INDEX ENABLE
);